### ISSUE TITLE
Variable names with underscore at the end break scala code

### ISSUE THREAD

**Issue by Randelung** [koofr/javatoscala#10]
When converting code with something like
```java
int i_ = 5;
```
the converter tries to output
```scala
val int_: Int = 5.
```
In an old version of the converter it would just return the invalid code, now it performs some sort of sanity check and recognizes the error (error: illegal start of simple pattern val i_: Int = 5 ^). A space between variable name and the colon would remove this issue.

**Comment by bancek** [comment]
Bugs should be reported to [scalagen library](https://github.com/timowest/scalagen). This is just a wrapper project.
