### ISSUE TITLE
Can't convert increment operator(++)

### ISSUE THREAD

**Issue by viliml** [koofr/javatoscala#3]
Things like

``` java
int i;
for (i=0; (double) i < 10.5; ++i) foo.bar()
```

translate to something like

``` scala
var i: Int
i = 0
while (i.toDouble < 10.5) {
    foo.bar()
    i
}
```

with the i alone in a line, not actually having anything done.

**Comment by Randelung** [comment]
The same goes with
```scala
for (int i = 0; i <= x; i++){}.
``` 
It's translated to
```scala
var i: Int = 0
while (i <= x) { i += 1; i - 1 }.
```

**Comment by bancek** [comment]
Bugs should be reported to [scalagen library](https://github.com/timowest/scalagen). This is just a wrapper project.
