### ISSUE TITLE
Initializations in constructor get reordered incorrectly

### ISSUE THREAD

**Issue by thSoft** [koofr/javatoscala#6]
The following Java Code:

```
public class Bug {

    final String fooName;

    public Bug() {
        final Object foo = new Object();
        fooName = foo.toString();
    }

}
```

gets compiled to the following Scala code:

```
class Bug {

  val fooName = foo.toString

  val foo = new AnyRef()
}
```

which obviously throws NPE since foo isn't yet initialized when toString() is called on it.

**Comment by bancek** [comment]
Bugs should be reported to [scalagen library](https://github.com/timowest/scalagen). This is just a wrapper project.
